version: "3.7"
services:
  postgres:
    build:
      context: /root/src/postgres/
      dockerfile: Dockerfile
    container_name: postgres
    ports:
      - 5432:5432
  nginx:
    build:
      context: /root/src/nginx/
      dockerfile: Dockerfile
    container_name: nginx
