version: "3.7"
services:
  postgres:
    image: postgres
    container_name: postgres
    environment:
      - "POSTGRES_PASSWORD=root"
      - "POSTGRES_USER=postgres"
    volumes:
      - "/root/src/postgres/sql:/docker-entrypoint-initdb.d"
    ports:
      - "5432:5432"
  nginx:
    image: nginx
    container_name: nginx
